language: php 
php: 
    - '5.6'
    - '7.0'
install:
    - composer install
script: "./scripts/run-tests.sh --debug"
git: 
    depth: 3    

notifications:
    email:
        on_success: never
        on_failure: never
